-- CreateTable
CREATE TABLE `users` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(63) NOT NULL,
    `email` VARCHAR(127) NOT NULL,
    `password` VARCHAR(127) NOT NULL,
    `birthAt` DATE NOT NULL,
    `createdAt` VARCHAR(45) NULL DEFAULT 'CURRENT_TIMESTAMP()',
    `updatedAt` VARCHAR(45) NULL DEFAULT 'CURRENT_TIMESTAMP()',

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
